version: '3.8'
services:
  api:
    build:
      context: ./api
      dockerfile: ./infrastructure/CheeseyPz.WebApi/Dockerfile
    ports:
      - "5006:5000"
    restart: always
  frontend:
    build:
      context: ./ui/CheeseyPz
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
